#!/bin/bash
touch "examples/$1.txt"
cat > "src/d$1.py" <<EOF
def prepare():
    
def part_one():
    
def test(input):
    assert true == true

def answer(input):
    print()
EOF
session=`cat .session`
day=$(echo $1 | sed 's/^0*//')
curl -s "https://adventofcode.com/2021/day/$day/input" \
    -H "Cookie: session=$session" \
    -o "inputs/$1.txt"
